services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    command: ["bash", "-c", "ollama pull llama3.1 && ollama serve"]

volumes:
  ollama_data:
